version: "3.9"
services:
  api:
    container_name: api.aascmed.com
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
