backend:
  name: git-gateway
  repo: m-salmankhan/aascmed-monorepo

display_url: https://new.aascmed.com
logo_url: https://new.aascmed.com/assets/favicon/favicon.svg

media_folder: aascmed.com/static/assets/uploads
public_folder: /assets/uploads

media_library:
  max_file_size: 5000000000
  folder_support: true

collections:
  - name: pages
    label: Pages
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: home
        file: aascmed.com/content/pages/home.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text

          - name: hero
            label: Hero
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown }

          - name: conditions
            label: Conditions Section
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown }

          - name: service-updates
            label: Service Updates
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown, required: false}

          - name: providers
            label: Providers Section
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown, required: false}

          - name: patient-feedback
            label: Patient Feedback Section
            widget: object
            fields:
              - { name: rating, label: Rating, widget: number, value_type: float }
              - { name: source-url, label: Source URL, widget: text}
              - { name: source-name, label: Source Name, widget: text}
              - { name: access-date, label: Access Date (Month, Year), widget: text}

          - name: practices
            label: Practices Section
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown, required: false}

          - name: contact
            label: Contact Section
            widget: object
            fields:
              - { name: heading, label: Heading, widget: text }
              - { name: text, label: Text, widget: markdown}


      - label: "Privacy"
        name: privacy
        file: aascmed.com/content/pages/privacy.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text
          - name: heading
            label: Heading
            widget: text
          - name: text
            label: Text
            widget: markdown
          - name: lastUpdated
            label: Last Updated
            widget: datetime
            date_format: 'yyyy.MM.dd'
            time_format: false

      - label: "Contact Page"
        name: contact
        file: aascmed.com/content/pages/contact.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text
          - name: heading
            label: Heading
            widget: text
          - name: text
            label: Text
            widget: markdown

      - label: "Conditions Index Page"
        name: conditions
        file: aascmed.com/content/pages/conditions.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text

          - name: heading
            label: Heading
            widget: text
          - name: text
            label: Text
            widget: markdown

      - label: "Providers Index Page"
        name: providers
        file: aascmed.com/content/pages/providers.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text

          - name: heading
            label: Heading
            widget: text
          - name: text
            label: Text
            widget: markdown

      - label: "Clinics Index Page"
        name: clinics
        file: aascmed.com/content/pages/clinics.yml
        fields:
          - name: meta_description
            label: "Meta Description"
            widget: text

          - name: heading
            label: Heading
            widget: text
          - name: text
            label: Text
            widget: markdown


  - name: conditions
    label: Conditions
    folder: aascmed.com/content/conditions
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    format: frontmatter
    extension: mdx
    create: true
    identifier_field: heading
    fields:
      - { name: title, label: Title  (for <title>)}
      - { name: heading, label: Heading (<h1> and archive display) }
      - { name: description, label: Description, widget: text }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
      - name: "faq"
        label: "Frequently Asked Questions"
        widget: "list"
        fields:
          - { name: question_heading_level, label: Question Heading Level, widget: number , min: 1, max: 6, step: 1}
          - { name: question, label: Question, widget: string }
          - { name: answer, label: Answer, widget: markdown }


  - name: service-updates
    label: Service Updates
    folder: aascmed.com/content/service-updates
    format: frontmatter
    extension: mdx
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title, }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: text }
      - { name: body, label: Body, widget: markdown }

  - name: providers
    label: Providers
    folder: aascmed.com/content/providers
    format: frontmatter
    extension: mdx
    create: true
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - name: "name"
        label: "Name"
        widget: "object"
        fields:
          - { name: fullname, label: Full Name }
          - { name: degree, label: Degree, widget: string, required: false }
          - { name: degree-abbr, label: Degree (Abbreviation), widget: string, required: false }
          - { name: title, label: Title, widget: string, required: false }
      - { name: image, label: Image, widget: image }
      - { name: review, label: Featured Review, widget: markdown }
      - { name: body, label: Body, widget: markdown }
      - { name: description, label: Description (Displayed under google search results), widget: text }
      - { name: order, label: Order (Lowest = First), widget: number, value_type: int, required: false, default: 0 }

  - name: reviews
    label: Reviews
    folder: aascmed.com/content/reviews
    format: frontmatter
    extension: mdx
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - name: "source"
        label: "Review Source"
        widget: "object"
        fields:
          - { name: url, label: URL, widget: string }
          - { name: name, label: Name, widget: string, required: false }
      - { name: stars, label: Stars, widget: number, min: 0, max: 5, step: 0.5 }
      - { name: body, label: Body, widget: markdown }

  - name: clinics
    label: Clinics
    folder: aascmed.com/content/clinics
    format: frontmatter
    extension: mdx
    create: true
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    identifier_field: clinic_name
    fields:
      - name: page_title
        label: Page Title
      - name: clinic_name
        label: Clinic Name
        widget: string
        required: true
      - name: description
        label: Description
        widget: text
      - name: "opening"
        label: "Opening Times"
        widget: "list"
        fields:
          - { name: day, label: Day, widget: string }
          - { name: hours, label: Hours, widget: string }
          - { name: notes, label: Notes, widget: string, required: false }
      - name: "shot"
        label: "Shot Times"
        widget: "list"
        fields:
          - { name: day, label: Day, widget: string }
          - { name: hours, label: Hours, widget: string }
          - { name: notes, label: Notes, widget: string, required: false }
      - { name: address, label: Address, widget: text }
      - { name: phone, label: Phone, widget: string }
      - { name: fax, label: Fax, widget: string }
      - { name: lat, label: Latitude, widget: number, value_type: float, step: 0.0001 }
      - { name: lon, label: Longitude, widget: number, value_type: float, step: 0.0001 }
      - { name: placeId, label: Google Maps Place ID, widget: string, isRequired: false }
      - { name: body, label: Body, widget: markdown, isRequired: false }
