on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v2
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run build
      # # 4. Deploy the gatsby build to Netlify
      # - uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   with:
      #     # 5. "gatsby build" creates "public" folder, which is what we are deploying
      #     args: deploy --dir=public --prod
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
