on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./aascmed.com

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # create .env.production
      - run: >
          echo "GATBSY_API_BASE_URL=${{ vars.GATBSY_API_BASE_URL }} >> .env.production
          echo "GATSBY_MAPBOX_API_KEY=${{ vars.GATSBY_MAPBOX_API_KEY }} >> .env.production

      - run: npm install
      
      - run: npm run build
      
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          # 5. "gatsby build" creates "public" folder, which is what we are deploying
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
